name: daily_essay
description: ecclgo test project

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #
  cupertino_icons: ^1.0.2
  #
  http: ^0.13.4
  intl: ^0.17.0
  provider: ^6.0.3
  image_downloader: ^0.31.0
  sqflite: ^2.0.2+1
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  json_annotation: ^4.5.0
  freezed_annotation: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  #
  flutter_lints: ^2.0.0
  #
  freezed: ^2.0.3+1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  sqflite_common_ffi: ^2.1.1

flutter:
  uses-material-design: true